# LINE Bot 設定
LINE_CHANNEL_ACCESS_TOKEN=你的LINE_CHANNEL_ACCESS_TOKEN
LINE_CHANNEL_SECRET=你的LINE_CHANNEL_SECRET

# Hugging Face API (可選，用於AI回覆)
HUGGINGFACE_API_KEY=你的HUGGINGFACE_API_KEY

# 伺服器設定
PORT=10000